STATUS:
	go run main.go status

MIGRATE-ALL:
	go run main.go migrate batch

MIGRATE-INC:
	go run main.go migrate inc

# DO NOT ENABLE THIS TO AVOID UNINTENDED DESTRUCTIVE OPERATIONS.
# 这里不打开是避免误操作导致问题
#MIGRATE-DEC:
#	go run main.go migrate dec
